# Generated by Django 5.0.14 on 2025-04-30 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_range", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
